### ISSUE TITLE
Plugin not included in your repo

### ISSUE THREAD

**Issue by fancymans** [KevinGutowski/NudgeRTL#1]
In addition to providing a separate download link, you should also include the plugin in your repo so that people who clone or fork from your repo can simply pull any changes you do in the future! :)

So I would remove:

```
# build artifacts 
plugin.sketchplugin
```

from the `.gitignore` file so that it gets added.

Also as a side note, you should consider renaming your plugin file to be more identifiable than `plugin.sketchplugin`.

**Comment by KevinGutowski** [comment]
Thanks a bunch for the feedback. Not sure if you are familiar with SKPM but I’m not entirely sure what part of the package.json that I need to modify so that I can rename the compiled plugin. If not, no worries. I can just do some trial and error to figure it out.

**Comment by KevinGutowski** [comment]
I think I was able to add the plugin file from the .gitignore and was able to rename the sketch plugin name. I’ll push a new version version of the plugin later tonight with some updated graphics.
